name: movie
description: A new Flutter project.
publish_to: 'none' 
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  analyzer: ^5.12.0
  dio: ^4.0.0
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  retrofit: ^3.0.1+1
  rxdart: ^0.27.7
  shared_preferences: ^2.1.1
  json_serializable: ^6.6.2
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  pretty_dio_logger: ^1.1.1
  freezed: ^2.3.4
  get_it: ^7.6.0
  lottie: ^2.3.2
  flutter_launcher_icons: ^0.13.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^4.0.1
  build_runner: ^2.3.3

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/demo-icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
  - assets/images/demo-icon.png
  - assets/json/error.json
  - assets/json/empty.json
  - assets/json/loading.json
  - assets/json/success.json
  fonts:
     - family: Cairo
       fonts:
         - asset: assets/fonts/Cairo-Black.ttf
           weight: 700
         - asset: assets/fonts/Cairo-Bold.ttf
           weight: 700
         - asset: assets/fonts/Cairo-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Cairo-Medium.ttf
           weight: 500
         - asset: assets/fonts/Cairo-Regular.ttf
           weight: 400
         - asset: assets/fonts/Cairo-Light.ttf
           weight: 300  